// <auto-generated />
using System;
using FunRunRegistration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunRunRegistration.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250117161953_Initial migration")]
    partial class Initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FunRunRegistration.Models.Entities.Address", b =>
                {
                    b.Property<int>("addressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("addressId"));

                    b.Property<string>("addressCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addressPostal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addressStreet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("addressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("FunRunRegistration.Models.Entities.Registrant", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("userAddressId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userBirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("userBirthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("userFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("userLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Registrants");
                });
#pragma warning restore 612, 618
        }
    }
}
